import os
import re

translations = {
    'en': {
        "Area Privata": "Private Area",
        "Benvenuto,": "Welcome,",
        "Statistiche": "Statistics",
        "Oggetti totali": "Total items",
        "Note private": "Private notes",
        "Prestiti attivi": "Active loans",
        "Note Recenti": "Recent Notes",
        "Nessuna nota ancora.": "No notes yet.",
        "Prestiti Attivi": "Active Loans",
        "Prestito a:": "Loan to:",
        "Dal:": "From:",
        "Ritorno previsto:": "Expected return:",
        "Nessun prestito attivo.": "No active loan.",
        "Notifiche": "Notifications",
        "Vedi Collezione": "View Collection",
        "Logout": "Logout",
        "Collezione": "Collection",
        "Epoche": "Eras",
        "Didattica": "Education",
        "Esplora Mappa": "Explore Map",
        "Ricerca": "Search",
        "Chi Siamo": "About Us",
        "Contatti": "Contacts",
        "Admin": "Admin",
        "Login": "Login",
        "Cerca oggetti, descrizioni, provenienza...": "Search items, descriptions, provenance...",
        "Cancella ricerca": "Clear search",
        "Cerca": "Search",
        "Collezione Completa": "Full Collection",
        "Risultati per": "Results for",
        "oggetti": "items",
        "Mostrando": "Showing",
        "di": "of",
        "Prima pagina": "First page",
        "Pagina precedente": "Previous page",
        "Pagina successiva": "Next page",
        "Ultima pagina": "Last page",
        "Pagina": "Page",
        "oggetti totali": "total items",
        "Vai a pagina:": "Go to page:",
        "Vai": "Go",
        "Torna alla collezione": "Back to collection",
        "Nota Privata": "Private Note",
        "Accedi all'area riservata per la famiglia": "Access the family private area",
        "Username": "Username",
        "Password": "Password",
        "Ricordami": "Remember me",
        "Accedi": "Login",
        "Torna alla home": "Back to home",
        "Torna all'oggetto": "Back to item",
        "Nota": "Note",
        "Aggiungi una nota privata per questo oggetto...": "Add a private note for this item...",
        "Salva Nota": "Save Note",
        "Annulla": "Cancel",
        "Torna all'Area Privata": "Back to Private Area",
        "Segna come letta": "Mark as read",
        "Vedi Oggetto": "View Item",
        "Nessuna notifica.": "No notifications.",
        "Ricerca Avanzata": "Advanced Search",
        "Testo": "Text",
        "Cerca nel titolo, descrizione...": "Search in title, description...",
        "Categoria": "Category",
        "Tutte": "All",
        "Regione": "Region",
        "Epoca": "Era",
        "Materiale": "Material",
        "Tutti": "All",
        "Anno da": "Year from",
        "Anno a": "Year to",
        "Stato Conservazione": "Conservation State",
        "Reset": "Reset",
        "Risultati": "Results",
        "Nessun risultato trovato.": "No results found.",
        "Vedi": "View"
    },
    'fr': {
        "Area Privata": "Espace Privé",
        "Benvenuto,": "Bienvenue,",
        "Statistiche": "Statistiques",
        "Oggetti totali": "Objets au total",
        "Note private": "Notes privées",
        "Prestiti attivi": "Prêts en cours",
        "Note Recenti": "Notes Récentes",
        "Nessuna nota ancora.": "Rien à afficher.",
        "Prestiti Attivi": "Prêts en Cours",
        "Prestito a:": "Prêté à:",
        "Dal:": "Du:",
        "Ritorno previsto:": "Retour prévu:",
        "Nessun prestito attivo.": "Aucun prêt en cours.",
        "Notifiche": "Notifications",
        "Vedi Collezione": "Voir Collection",
        "Logout": "Déconnexion",
        "Collezione": "Collection",
        "Epoche": "Époques",
        "Didattica": "Éducation",
        "Esplora Mappa": "Explorer la Carte",
        "Ricerca": "Recherche",
        "Chi Siamo": "À Propos",
        "Contatti": "Contacts",
        "Admin": "Admin",
        "Login": "Connexion",
        "Cerca oggetti, descrizioni, provenienza...": "Rechercher des objets...",
        "Cancella ricerca": "Effacer",
        "Cerca": "Chercher",
        "Collezione Completa": "Collection Complète",
        "Risultati per": "Résultats pour",
        "oggetti": "objets",
        "Mostrando": "Affichage",
        "di": "sur",
        "Prima pagina": "Première page",
        "Pagina precedente": "Page précédente",
        "Pagina successiva": "Page suivante",
        "Ultima pagina": "Dernière page",
        "Pagina": "Page",
        "oggetti totali": "objets au total",
        "Vai a pagina:": "Aller à la page:",
        "Vai": "Aller",
        "Torna alla collezione": "Retour à la collection",
        "Nota Privata": "Note Privée",
        "Accedi all'area riservata per la famiglia": "Accéder à l'espace familial",
        "Username": "Nom d'utilisateur",
        "Password": "Mot de passe",
        "Ricordami": "Se souvenir de moi",
        "Accedi": "Connexion",
        "Torna alla home": "Retour à l'accueil",
        "Torna all'oggetto": "Retour à l'objet",
        "Nota": "Note",
        "Aggiungi una nota privata per questo oggetto...": "Ajouter une note privée...",
        "Salva Nota": "Enregistrer la Note",
        "Annulla": "Annuler",
        "Torna all'Area Privata": "Retour à l'Espace Privé",
        "Segna come letta": "Marquer comme lu",
        "Vedi Oggetto": "Voir Objet",
        "Nessuna notifica.": "Aucune notification.",
        "Ricerca Avanzata": "Recherche Avancée",
        "Testo": "Texte",
        "Cerca nel titolo, descrizione...": "Chercher dans le titre...",
        "Categoria": "Catégorie",
        "Tutte": "Toutes",
        "Regione": "Région",
        "Epoca": "Époque",
        "Materiale": "Matériel",
        "Tutti": "Tous",
        "Anno da": "Année de",
        "Anno a": "Année à",
        "Stato Conservazione": "État de Conservation",
        "Reset": "Réinitialiser",
        "Risultati": "Résultats",
        "Nessun risultato trovato.": "Aucun résultat trouvé.",
        "Vedi": "Voir"
    },
    'es': {
        "Area Privata": "Área Privada",
        "Benvenuto,": "Bienvenido,",
        "Statistiche": "Estadísticas",
        "Oggetti totali": "Objetos totales",
        "Note private": "Notas privadas",
        "Prestiti attivi": "Préstamos activos",
        "Note Recenti": "Notas Recientes",
        "Nessuna nota ancora.": "Aún sin notas.",
        "Prestiti Attivi": "Préstamos Activos",
        "Prestito a:": "Préstamo a:",
        "Dal:": "Desde:",
        "Ritorno previsto:": "Retorno previsto:",
        "Nessun prestito attivo.": "Sin préstamos activos.",
        "Notifiche": "Notificaciones",
        "Vedi Collezione": "Ver Colección",
        "Logout": "Cerrar Sesión",
        "Collezione": "Colección",
        "Epoche": "Épocas",
        "Didattica": "Educación",
        "Esplora Mappa": "Explorar Mapa",
        "Ricerca": "Búsqueda",
        "Chi Siamo": "Sobre Nosotros",
        "Contatti": "Contactos",
        "Admin": "Admin",
        "Login": "Iniciar Sesión",
        "Cerca oggetti, descrizioni, provenienza...": "Buscar objetos, descripciones...",
        "Cancella ricerca": "Borrar búsqueda",
        "Cerca": "Buscar",
        "Collezione Completa": "Colección Completa",
        "Risultati per": "Resultados para",
        "oggetti": "objetos",
        "Mostrando": "Mostrando",
        "di": "de",
        "Prima pagina": "Primera página",
        "Pagina precedente": "Página anterior",
        "Pagina successiva": "Página siguiente",
        "Ultima pagina": "Última página",
        "Pagina": "Página",
        "oggetti totali": "objetos totales",
        "Vai a pagina:": "Ir a la página:",
        "Vai": "Ir",
        "Torna alla collezione": "Volver a la colección",
        "Nota Privata": "Nota Privada",
        "Accedi all'area riservata per la famiglia": "Accede al área reservada familiar",
        "Username": "Usuario",
        "Password": "Contraseña",
        "Ricordami": "Recuérdame",
        "Accedi": "Ingresar",
        "Torna alla home": "Volver a inicio",
        "Torna all'oggetto": "Volver al objeto",
        "Nota": "Nota",
        "Aggiungi una nota privata per questo oggetto...": "Agrega una nota privada...",
        "Salva Nota": "Guardar Nota",
        "Annulla": "Cancelar",
        "Torna all'Area Privata": "Volver al Área Privada",
        "Segna come letta": "Marcar como leída",
        "Vedi Oggetto": "Ver Objeto",
        "Nessuna notifica.": "Sin notificaciones.",
        "Ricerca Avanzata": "Búsqueda Avanzada",
        "Testo": "Texto",
        "Cerca nel titolo, descrizione...": "Buscar en el título...",
        "Categoria": "Categoría",
        "Tutte": "Todas",
        "Regione": "Región",
        "Epoca": "Época",
        "Materiale": "Material",
        "Tutti": "Todos",
        "Anno da": "Año desde",
        "Anno a": "Año hasta",
        "Stato Conservazione": "Estado de Conservación",
        "Reset": "Reiniciar",
        "Risultati": "Resultados",
        "Nessun risultato trovato.": "No se encontraron resultados.",
        "Vedi": "Ver"
    },
    'de': {
        "Area Privata": "Privatbereich",
        "Benvenuto,": "Willkommen,",
        "Statistiche": "Statistiken",
        "Oggetti totali": "Gesamtobjekte",
        "Note private": "Private Notizen",
        "Prestiti attivi": "Aktive Ausleihen",
        "Note Recenti": "Letzte Notizen",
        "Nessuna nota ancora.": "Noch keine Notizen.",
        "Prestiti Attivi": "Aktive Ausleihen",
        "Prestito a:": "Ausgeliehen an:",
        "Dal:": "Von:",
        "Ritorno previsto:": "Geplante Rückkehr:",
        "Nessun prestito attivo.": "Keine aktive Ausleihe.",
        "Notifiche": "Benachrichtigungen",
        "Vedi Collezione": "Sammlung anzeigen",
        "Logout": "Ausloggen",
        "Collezione": "Sammlung",
        "Epoche": "Epochen",
        "Didattica": "Bildung",
        "Esplora Mappa": "Karte Erkunden",
        "Ricerca": "Suche",
        "Chi Siamo": "Über uns",
        "Contatti": "Kontakte",
        "Admin": "Admin",
        "Login": "Einloggen",
        "Cerca oggetti, descrizioni, provenienza...": "Suchen nach Objekten...",
        "Cancella ricerca": "Suche löschen",
        "Cerca": "Suchen",
        "Collezione Completa": "Komplette Sammlung",
        "Risultati per": "Ergebnisse für",
        "oggetti": "Objekte",
        "Mostrando": "Anzeigen",
        "di": "von",
        "Prima pagina": "Erste Seite",
        "Pagina precedente": "Vorherige Seite",
        "Pagina successiva": "Nächste Seite",
        "Ultima pagina": "Letzte Seite",
        "Pagina": "Seite",
        "oggetti totali": "Gesamtobjekte",
        "Vai a pagina:": "Gehe zu Seite:",
        "Vai": "Los",
        "Torna alla collezione": "Zurück zur Sammlung",
        "Nota Privata": "Private Notiz",
        "Accedi all'area riservata per la famiglia": "Greifen Sie auf den Familienbereich zu",
        "Username": "Benutzername",
        "Password": "Passwort",
        "Ricordami": "Erinnere dich an mich",
        "Accedi": "Einloggen",
        "Torna alla home": "Zurück zur Startseite",
        "Torna all'oggetto": "Zurück zum Objekt",
        "Nota": "Notiz",
        "Aggiungi una nota privata per questo oggetto...": "Private Notiz hinzufügen...",
        "Salva Nota": "Notiz Speichern",
        "Annulla": "Abbrechen",
        "Torna all'Area Privata": "Zurück zum Privatbereich",
        "Segna come letta": "Als gelesen markieren",
        "Vedi Oggetto": "Objekt ansehen",
        "Nessuna notifica.": "Keine Benachrichtigung.",
        "Ricerca Avanzata": "Erweiterte Suche",
        "Testo": "Text",
        "Cerca nel titolo, descrizione...": "Suchen im Titel, in der Beschreibung...",
        "Categoria": "Kategorie",
        "Tutte": "Alle",
        "Regione": "Region",
        "Epoca": "Epoche",
        "Materiale": "Material",
        "Tutti": "Alle",
        "Anno da": "Jahr von",
        "Anno a": "Jahr bis",
        "Stato Conservazione": "Erhaltungszustand",
        "Reset": "Zurücksetzen",
        "Risultati": "Ergebnisse",
        "Nessun risultato trovato.": "Kein Ergebnis gefunden.",
        "Vedi": "Anzeigen"
    }
}

base_dir = "translations"
for lang, trans_dict in translations.items():
    po_path = os.path.join(base_dir, lang, "LC_MESSAGES", "messages.po")
    if not os.path.exists(po_path):
        continue
    
    with open(po_path, 'r', encoding='utf-8') as f:
        content = f.read()

    for eng_id, translated_str in trans_dict.items():
        safe_id = eng_id.replace('"', '\\"')
        safe_trans = translated_str.replace('"', '\\"')
        # We need to selectively replace only if msgstr is completely empty or to overwrite
        pattern = r'msgid "' + re.escape(safe_id) + r'"\nmsgstr "[^"]*"'
        replacement = 'msgid "' + safe_id + '"\nmsgstr "' + safe_trans + '"'
        content = re.sub(pattern, replacement, content)

    with open(po_path, 'w', encoding='utf-8') as f:
        f.write(content)
    print(f"Processed translations for {lang}")
